name: Build/Deploy

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint requests tinydb python-dotenv lxml
    - name: Deploy static content to S3
      run: |
        pylint $(git ls-files '*.py')
