name: Build/Deploy

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Pull Request Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint requests tinydb python-dotenv lxml json_log_formatter
    - name: Create dummy .env file
      run: |
        cat <<EOT > .env
        NF_IDENTIFIER=ANF
        TELEGRAM_BOT_ID=False
        TELEGRAM_BOT_SECRET=False
        TELEGRAM_CHAT_ID=False
        EOT
    - name: Run FireBot without env vars just to populate its DB
      run: |
        python3 firebot.py debug mock
    - name: Create real .env file
      env:
        NF_IDENTIFIER: ${{ secrets.NF_IDENTIFIER }}
        TELEGRAM_BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
        TELEGRAM_BOT_SECRET: ${{ secrets.TELEGRAM_BOT_SECRET }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        cat <<EOT > .env
        NF_IDENTIFIER=${NF_IDENTIFIER}
        TELEGRAM_BOT_ID=${TELEGRAM_BOT_ID}
        TELEGRAM_BOT_SECRET=${TELEGRAM_BOT_SECRET}
        TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
        EOT

    - name: Remove last entry
      run: |
        cd .github/workflows/
        python3 remove-last-entry.py
    - name: Test 1
      env:
        TELEGRAM_BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
        TELEGRAM_BOT_SECRET: ${{ secrets.TELEGRAM_BOT_SECRET }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        TEXT='NOTICE: TEST 1, New Incident'
        curl -s "https://api.telegram.org/${TELEGRAM_BOT_ID}:${TELEGRAM_BOT_SECRET}/sendMessage?chat_id=${TELEGRAM_CHAT_ID}&text=${TEXT}"
    - name: Scenario 1 Run
      run: |
        python3 firebot.py debug mock

    - name: Modify last entry
      run: |
        cd .github/workflows/
        python3 modify-an-entry.py
    - name: Test 2
      env:
        TELEGRAM_BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
        TELEGRAM_BOT_SECRET: ${{ secrets.TELEGRAM_BOT_SECRET }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        TEXT='NOTICE: TEST 2, Changed Incident'
        curl -s "https://api.telegram.org/${TELEGRAM_BOT_ID}:${TELEGRAM_BOT_SECRET}/sendMessage?chat_id=${TELEGRAM_CHAT_ID}&text=${TEXT}"
    - name: Run FireBot to generate test notif.
      run: |
        python3 firebot.py debug mock
